name: CONTINUOUS DELIVERY AND DEPLOYMENT FOR STAGING

on:
  push:
    branches:
      - 'staging/v*'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Staging

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Login In To Docker
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Set Docker Tag
        id: tag
        run: echo "TAG=staging-${GITHUB_REF_NAME#staging/}" >> $GITHUB_OUTPUT
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
      - name: Build The Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            abdullah00001/workly-contacts:${{ steps.tag.outputs.TAG }}
            abdullah00001/workly-contacts:staging-latest
      - name: Deploy to Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
